site_name: Jas Documentation

docs_dir: reference
theme:
  name: readthedocs

plugins:
  - "gh-admonitions"
  - search

markdown_extensions:
  - admonition

# Please note: The `nav` property must be reserved ton the
# final property as the entry `reference`'s members would
# be populated by appending data via a script.

nav: