site_name: Jas Documentation
logo: img/logo.png

docs_dir: jas-doc/
theme:
  name: readthedocs

plugins:
  - "gh-admonitions"
  - search

markdown_extensions:
  - admonition

# Please note: The `nav` property must be reserved ton the
# final property as the entry `reference`'s members would
# be populated by appending data via a script.

nav:
